### ISSUE TITLE
Windows 7 compatibility

### ISSUE THREAD

**Issue by ghost** [sandboxie-plus/sandboxie-plus.github.io#1]
Does Sandboxie-Plus compatible with Windows 7? Sandboxie-Plus MUST support Windows 7 because of end-of-support. I hope from the developer to CONFIRM Windows 7 support on the official Sandboxie-Plus website.

**Comment by DavidXanatos** [comment]
Yes it supports windows 7 and it will do that longer than MSFT does LOL
