### ISSUE TITLE
Feature request: Sandboxie plus Shortcut Key

### ISSUE THREAD

**Issue by Mored4u** [sandboxie-plus/sandboxie-plus.github.io#2]
Need Shortcut Key to do some action like (Press F4 = Terminate All Programs)

![image](https://user-images.githubusercontent.com/5413459/122674273-10841000-d1dd-11eb-8b80-61e8b5bc16a1.png)

**Comment by isaak654** [comment]
Main repository is here:
https://github.com/sandboxie-plus/Sandboxie/issues

**Comment by Mored4u** [comment]
![image](https://user-images.githubusercontent.com/5413459/124620496-2acb1880-de82-11eb-8618-5124f9def508.png)

Excellent feature
